//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public Author()
        {
            this.Blogentries = new HashSet<Blogentries>();
            this.Blogtypes = new HashSet<Blogtypes>();
            this.Files = new HashSet<Files>();
            this.Logs = new HashSet<Logs>();
            this.Personsettings = new HashSet<Personsettings>();
        }
    
        public int author_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int role_id { get; set; }
        public string islock { get; set; }
        public string email { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<Blogentries> Blogentries { get; set; }
        public virtual ICollection<Blogtypes> Blogtypes { get; set; }
        public virtual ICollection<Files> Files { get; set; }
        public virtual ICollection<Logs> Logs { get; set; }
        public virtual ICollection<Personsettings> Personsettings { get; set; }
    }
}
