//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog_Tags
    {
        public int blog_tag_id { get; set; }
        public int tag_id { get; set; }
        public int blog_id { get; set; }
    
        public virtual Blogentries Blogentries { get; set; }
        public virtual Tags Tags { get; set; }
    }
}
