//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int comment_id { get; set; }
        public string author { get; set; }
        public Nullable<int> blog_id { get; set; }
        public string ip { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<System.DateTime> datemodified { get; set; }
        public string body { get; set; }
        public string islock { get; set; }
    
        public virtual Blogentries Blogentries { get; set; }
    }
}
