//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public Model()
        {
            this.Personsettings = new HashSet<Personsettings>();
        }
    
        public int model_id { get; set; }
        public string name { get; set; }
        public string path { get; set; }
    
        public virtual ICollection<Personsettings> Personsettings { get; set; }
    }
}
