//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tags
    {
        public Tags()
        {
            this.Blog_Tags = new HashSet<Blog_Tags>();
        }
    
        public int tag_id { get; set; }
        public string tagName { get; set; }
    
        public virtual ICollection<Blog_Tags> Blog_Tags { get; set; }
    }
}
